###
# File: fluent-bit.global-filters.yaml
# Project: fluent-bit
# Description: Global Lua filters executed AFTER all input-specific filters
###

parsers:
  - name: json
    format: json

pipeline:
  filters:
    # Ensure all logs are formatted correctly (runs after input-specific filters)
    - name: lua
      match_regex: ^(?!.*_fmt\.).*
      script: apply_standard_record_formatting.lua
      call: standard_record_formatting
      time_as_table: true
